DROP TABLE IF EXISTS WROX_PENDING;
DROP TABLE IF EXISTS WROX_USER;

CREATE TABLE WROX_USER (
	USER_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT, 
	USERNAME VARCHAR(20) NOT NULL, 
	PASSWORD CHAR(40) NOT NULL, 
	EMAIL_ADDR VARCHAR(100) NOT NULL, 
	IS_ACTIVE TINYINT(1) DEFAULT 0, 
	PRIMARY KEY (USER_ID) 
)ENGINE=MyISAM DEFAULT CHARACTER SET utf8;

CREATE TABLE WROX_PENDING (
	USER_ID INTEGER UNSIGNED PRIMARY KEY NOT NULL, 
	TOKEN CHAR(10) NOT NULL, 
	CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	FOREIGN KEY (USER_ID) 
	REFERENCES WROX_USER(USER_ID) 
)ENGINE=MyISAM DEFAULT CHARACTER SET utf8;